// This file contains methods that existed in a previous version of Redot in ClassDB but were removed
// or their method signature has changed so they are no longer generated by bindings_generator.
// These methods are provided to avoid breaking binary compatibility.

using System;
using System.ComponentModel;

namespace Redot;

// TODO: This is currently disabled because of https://github.com/dotnet/roslyn/issues/52904
#pragma warning disable IDE0040 // Add accessibility modifiers.

partial class EditorUndoRedoManager
{
    /// <inheritdoc cref="CreateAction(string, UndoRedo.MergeMode, RedotObject, bool)"/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public void CreateAction(string name, UndoRedo.MergeMode mergeMode, RedotObject customContext)
    {
        CreateAction(name, mergeMode, customContext, backwardUndoOps: false);
    }
}
